/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef createDb_CONSTANTS_H
#define createDb_CONSTANTS_H

#include "createDb_types.h"



class createDbConstants {
 public:
  createDbConstants();

};

extern const createDbConstants g_createDb_constants;



#endif
