/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "createDb_constants.h"



const createDbConstants g_createDb_constants;

createDbConstants::createDbConstants() {
}



