/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef updateDatabase_CONSTANTS_H
#define updateDatabase_CONSTANTS_H

#include "updateDatabase_types.h"



class updateDatabaseConstants {
 public:
  updateDatabaseConstants();

};

extern const updateDatabaseConstants g_updateDatabase_constants;



#endif
