/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "updateDatabase_constants.h"



const updateDatabaseConstants g_updateDatabase_constants;

updateDatabaseConstants::updateDatabaseConstants() {
}



