/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "withReturn_constants.h"



const withReturnConstants g_withReturn_constants;

withReturnConstants::withReturnConstants() {
}



