/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef withReturn_CONSTANTS_H
#define withReturn_CONSTANTS_H

#include "withReturn_types.h"



class withReturnConstants {
 public:
  withReturnConstants();

};

extern const withReturnConstants g_withReturn_constants;



#endif
